Person and vehicle transformation

In [ ]:
import pandas as pd
import mysql.connector
from mysql.connector import Error

# Database connection parameters
db_config = {
    'host': 'localhost',
    'user': 'root',
    'password': 'Gouthi321@',  # Replace with your actual password
    'database': 'crash_data'
}

# Connect to the database
try:
    connection = mysql.connector.connect(**db_config)
    if connection.is_connected():
        db_info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_info)
        cursor = connection.cursor()

        # Read the crashed data
        crashes_df = pd.read_csv('mv_crashes_cleaned.csv')
        collision_ids = crashes_df['COLLISION_ID'].unique()

        # Read and insert data for the person table
        person_file_path = 'person_cleaned.csv'
        chunksize = 50000  # Adjust the chunksize as per your system's capability
        person_insert_query = """
        INSERT INTO person (
            UNIQUE_ID, COLLISION_ID, CRASH_DATE, CRASH_TIME, PERSON_ID,
            PERSON_TYPE, PERSON_INJURY, VEHICLE_ID, PERSON_AGE, EJECTION,
            EMOTIONAL_STATUS, BODILY_INJURY, POSITION_IN_VEHICLE,
            SAFETY_EQUIPMENT, PED_LOCATION, PED_ACTION, COMPLAINT,
            PED_ROLE, CONTRIBUTING_FACTOR_1, CONTRIBUTING_FACTOR_2,
            PERSON_SEX
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """

        for chunk in pd.read_csv(person_file_path, chunksize=chunksize):
            chunk = chunk[chunk['COLLISION_ID'].isin(collision_ids)]
            person_data = [tuple(x) for x in chunk.to_numpy()]
            cursor.executemany(person_insert_query, person_data)
            connection.commit()
            print(f"Inserted {cursor.rowcount} rows into the person table.")

        # Read and insert data for the vehicles table
        vehicles_file_path = 'final_cleaned_vehicles_data.csv'
        vehicles_insert_query = """
        INSERT INTO vehicles (
            UNIQUE_ID, COLLISION_ID, CRASH_DATE, CRASH_TIME, VEHICLE_ID,
            STATE_REGISTRATION, VEHICLE_TYPE, VEHICLE_MAKE, VEHICLE_MODEL,
            VEHICLE_YEAR, TRAVEL_DIRECTION, VEHICLE_OCCUPANTS,
            DRIVER_LICENSE_STATUS, DRIVER_LICENSE_JURISDICTION,
            PRE_CRASH, POINT_OF_IMPACT, VEHICLE_DAMAGE, VEHICLE_DAMAGE_1,
            VEHICLE_DAMAGE_2, VEHICLE_DAMAGE_3, PUBLIC_PROPERTY_DAMAGE,
            PUBLIC_PROPERTY_DAMAGE_TYPE, CONTRIBUTING_FACTOR_1,
            CONTRIBUTING_FACTOR_2
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """

        for chunk in pd.read_csv(vehicles_file_path, chunksize=chunksize):
            chunk = chunk[chunk['COLLISION_ID'].isin(collision_ids)]
            chunk = chunk.where(pd.notnull(chunk), None)  # Replace NaN with None
            vehicles_data = [tuple(x) for x in chunk.to_numpy()]

            try:
                cursor.executemany(vehicles_insert_query, vehicles_data)
                connection.commit()
                print(f"Inserted {cursor.rowcount} rows into the vehicles table.")
            except Error as e:
                print(f"Error inserting data into the vehicles table: {e}")
                connection.rollback()
                print("Skipping the problematic chunk and continuing with the next one.")
                continue

except Error as e:
    print("Error while connecting to MySQL", e)
finally:
    if connection.is_connected():
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

crashes table insert statement

In [ ]:
import pandas as pd
import mysql.connector
from mysql.connector import Error

# Database connection parameters
db_config = {
    'host': 'localhost',
    'user': 'root',
    'password': 'Gouthi321@',  # Replace with your actual password
    'database': 'mv_collisions_database'
}

# Connect to the database
try:
    connection = mysql.connector.connect(**db_config)
    if connection.is_connected():
        db_info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_info)
        cursor = connection.cursor()

        #  file path to your CSV file
        csv_file_path = '/Users/gouthamvemula/Downloads/Motor_Vehicle_Collisions_-_Crashes_20240425 (2).csv'  # Replace with the actual file path

        # Read and insert data in chunks
        chunksize = 15000  # Adjust chunksize as per your system's capability
        for chunk in pd.read_csv(csv_file_path, chunksize=chunksize, dtype=str):
            # Replace NaN with None and convert strings to floats for lat and lon
            chunk = chunk.where(pd.notna(chunk), None)
            chunk['LATITUDE'] = pd.to_numeric(chunk['LATITUDE'], errors='coerce')
            chunk['LONGITUDE'] = pd.to_numeric(chunk['LONGITUDE'], errors='coerce')

            # Format date columns
            chunk['CRASH DATE'] = pd.to_datetime(chunk['CRASH DATE'], errors='coerce').dt.strftime('%Y-%m-%d')

            # Filter out invalid latitudes and longitudes
            chunk = chunk[(chunk['LATITUDE'].between(-90, 90)) & (chunk['LONGITUDE'].between(-180, 180))]

            # Prepare location data
            chunk['LOCATION'] = chunk.apply(lambda x: f'POINT({x["LONGITUDE"]} {x["LATITUDE"]})' if pd.notna(x['LONGITUDE']) and pd.notna(x['LATITUDE']) else None, axis=1)

            # Convert the DataFrame to a list of tuples
            data_tuples = [tuple(x) for x in chunk.to_numpy()]

            # Prepare the insert statement based on the table columns
            insert_query = """
            INSERT INTO Crashes (
                `CRASH DATE`, `CRASH TIME`, `BOROUGH`, `ZIP CODE`, `LATITUDE`, `LONGITUDE`,
                `LOCATION`, `ON STREET NAME`, `CROSS STREET NAME`, `OFF STREET NAME`, 
                `NUMBER OF PERSONS INJURED`, `NUMBER OF PERSONS KILLED`,
                `NUMBER OF PEDESTRIANS INJURED`, `NUMBER OF PEDESTRIANS KILLED`, 
                `NUMBER OF CYCLIST INJURED`, `NUMBER OF CYCLIST KILLED`, 
                `NUMBER OF MOTORIST INJURED`, `NUMBER OF MOTORIST KILLED`,
                `CONTRIBUTING FACTOR VEHICLE 1`, `CONTRIBUTING FACTOR VEHICLE 2`, 
                `CONTRIBUTING FACTOR VEHICLE 3`, `CONTRIBUTING FACTOR VEHICLE 4`, 
                `CONTRIBUTING FACTOR VEHICLE 5`, `COLLISION_ID`,
                `VEHICLE TYPE CODE 1`, `VEHICLE TYPE CODE 2`, `VEHICLE TYPE CODE 3`, 
                `VEHICLE TYPE CODE 4`, `VEHICLE TYPE CODE 5`
            ) VALUES (%s, %s, %s, %s, %s, %s, ST_GeomFromText(%s, 4326), %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            
            # Execute the insert query
            cursor.executemany(insert_query, data_tuples)
            connection.commit()
            print(f"Inserted {cursor.rowcount} rows into Crashes table.")

except Error as e:
    print("Error while connecting to MySQL", e)
finally:
    if connection.is_connected():
        cursor.close()
        connection.close()
        print("MySQL connection is closed")